### ISSUE TITLE
Clean folder structure within container

### ISSUE THREAD

**Issue by ofrei** [comorment/gwas#11]
Currently all tools are placed in the root of the container:
![image](https://user-images.githubusercontent.com/13171449/97229346-8237c580-17d8-11eb-84db-ffcf4349922a.png)
I think it's best to have a separate folder for each tool, perhaps under a common top-level folder such as /tools. This would correspond to a structure like this:
```
/tools/flashpca-build   
/tools/generic-metal    
/tools/HDL                   
/tools/gctb_2.02_Linux  
/tools/htslib 
/tools/bcftools
/tools/vcftools
/tools/qctool_v2.0.6-Ubuntu16.04-x86_64
/tools/python_convert
/tools/BOLT-LMM_v2.3.4 
```
Further, I suggest to remote from the path things like "generic-", "_Linux"  "-Ubuntu16.04-x86_64", to have a clean name of the tool.  As for the versions, I think it's good to setup a specific nomenclature, i.e. similar to how it's done on TSD:
![image](https://user-images.githubusercontent.com/13171449/97230292-fb83e800-17d9-11eb-868a-cae56edafb5c.png)

**Comment by bayramakdeniz** [comment]
The structure of the container has been modified.

**Comment by ofrei** [comment]
I agree that binary executables should be copied into the ``/bin`` within the container, this is a good approach.

When installing software, I think it's important to keep the root folder clean.  I think ``WORKDIR`` docker command is the right tool  to achieve this. Also, I  suggest to put the instructions of each tool into a separate script. For example, ``install_plink.sh`` containing this:
```
#!/bin/sh
wget https://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20200616.zip
unzip -j plink_linux_x86_64_20200616.zip
rm -rf plink_linux_x86_64_20200616.zip
cp /plink  /bin
```

and ``install_prsice.sh``
```
#!/bin/sh
wget https://github.com/choishingwan/PRSice/releases/download/2.3.3/PRSice_linux.zip
unzip PRSice_linux.zip
rm -rf PRSice_linux.zip

# dataset for prsice
RUN wget https://5c2d08d4-17d1-4dd8-bb49-f9593683e642.filesusr.com/archives/e7bc47_f74626b357ed453584e9e775713fe9ac.zip?dn=data_chapter10.zip
unzip -j  e7bc47_f74626b357ed453584e9e775713fe9ac.zip?dn=data_chapter10.zip 
rm -rf   e7bc47_f74626b357ed453584e9e775713fe9ac.zip?dn=data_chapter10.zip
cp /PRSice_linux /bin
```

Following https://stackoverflow.com/questions/34549859/run-a-script-in-dockerfile I would organize Dockerfile as follows:

```
WORKDIR /tools/plink
ADD install_plink.sh
RUN chmod +x install_plink.sh

WORKDIR /tools/prsice
ADD install_prsice.sh
RUN chmod +x install_prsice.sh

# ... (continue with other software)
```

Note that ``install_plink.sh`` and ``install_prsice.sh`` already contain ``cp <software> /bin`` command.

I think this way it's easier to develop container because one can test and update specific installation instructions locally, but running a ``.sh`` script. Also this will take care of files left in the root folder.

![image](https://user-images.githubusercontent.com/13171449/98828178-0e342900-2438-11eb-9f9b-8f3a10c07234.png)
![image](https://user-images.githubusercontent.com/13171449/98828257-2310bc80-2438-11eb-80aa-5e515402d30d.png)

**Comment by ofrei** [comment]
@bayramakdeniz I haven't tested the above approach, just put it together to illustrate my suggestion- but hopefully it's possible to make this work (``WORKDIR /tools/prsice, ADD install_prsice.sh, RUN chmod +x install_prsice.sh``)

**Comment by bayramakdeniz** [comment]
Per your suggestion, the structure has been changed. All .sh files are put in a separate folder called scripts

**Comment by ofrei** [comment]
Thanks! Looks good, closing the ticket.
