### ISSUE TITLE
Conceptual question: which tools fit together into one container?

### ISSUE THREAD

**Issue by ofrei** [comorment/gwas#12]
What is our policy for putting together multiple tools into one container? Obviously all potential tools won't fit into one container. I see pros and cons of distributing tools into multiple containers:

Pros:
- it's good to keep the size of container low (in terms of GB it occupy on disk)
- it's faster to re-build container  from it's Docker file
- it helps to avoid conflicting dependencies

Cons:
-  if software share the same pre-requisites (i.e. standard python or R packages) it's good to place it to one container. 
-  if software is  just a binaries (i.e. plink, king, gcta, metal, etc) it's convenient for the user to have it in one container.

I hope it won't be too much work to re-arrange tools into multiple containers  once we learn what fits together.

**Comment by ofrei** [comment]
We can look how broadinstitute splits their stuff into containers https://hub.docker.com/u/broadinstitute?page=1

**Comment by ofrei** [comment]
After playing hands-on with singularity I further split ``conda.sif`` container into ``python3`` and ``ldsc`` containers, see these two commits:
https://github.com/comorment/gwas/commit/2a400163baa1d7bcf7ad3ce9c5bf4ad5bd776d48 and https://github.com/comorment/gwas/commit/0640a07ce7b2160b9e426bc9655f809ea2fc7b1a .
Then user saves typing ``source activate <environment>`` command, which is easy to forget.
Also, I like to have one sequential stream of ``conda install`` commands in the Docker file (https://github.com/comorment/gwas/blob/main/containers/python3/Dockerfile ) , all ``conda install`` dealing with the same environment. Then, if we keep ``conda install`` commands close to the end, it's easy to add new packages (and container will compile incrementally).
@bayramakdeniz please close this ticket if you agree with latest distribution of tools into containers. It's OK for me to  revise it later, after we gain more experience.

**Comment by bayramakdeniz** [comment]
I checked and run all containers. They all work successfully.
