### ISSUE TITLE
include GNU parallel 

### ISSUE THREAD

**Issue by ofrei** [comorment/gwas#15]
I suggest to add https://www.gnu.org/software/parallel/ to the container - it's a fairly standard tool, and it's very useful.

**Comment by bayramakdeniz** [comment]
"parallel" command has been added to the containers

**Comment by ofrei** [comment]
I see that both "parallel" and "less" are available in the container - thank for including them! But I'm not sure how it worked - which part of the Docker file made those tools available?
https://github.com/comorment/gwas/blob/main/Dockerfile

**Comment by bayramakdeniz** [comment]
You are right, I forgot to update the Dockerfile. You can see them now.

**Comment by ofrei** [comment]
:+1:
