### ISSUE TITLE
Make container with LD score regression

### ISSUE THREAD

**Issue by ofrei** [comorment/gwas#18]
I might need https://github.com/bulik/ldsc in a separate Docker container.
https://hub.docker.com/r/manninglab/ldsc/dockerfile - could this be a starting point?

**Comment by bayramakdeniz** [comment]
this can be done with a separate container: https://github.com/bayramakdeniz/ldsc

**Comment by ofrei** [comment]
The ldsc.sif runs fine, but https://github.com/bayramakdeniz/ldsc doesn't have Dockerfile - could you please add it?\
Also, we'll need to organize reference data  required for LD Score Regression.
It's available here: https://alkesgroup.broadinstitute.org/LDSCORE but we don't need all of it.
Some relevant data files are mentioned in here:
 https://github.com/bulik/ldsc/wiki/Heritability-and-Genetic-Correlation 
I've already worked with LDSC so I can help to select the files that are needed. Could you organize Dockerfile in a way that I suggested here https://github.com/comorment/gwas/issues/11 (i.e. to have a ``install_ldsc.sh`` script that is then used from within Dockerfile ?). I will then directly update ``install_ldsc.sh`` with all files that should came together with LDSC container.

**Comment by bayramakdeniz** [comment]
The Dockerfile for LDSC has been added. It includes 3 parts (some basic tools, miniconda and install_ldsc.sh)

**Comment by ofrei** [comment]
@bayramakdeniz Thanks! I'll test it out.

**Comment by ofrei** [comment]
I've tested it out and it works well. Let's discuss on Wednesday, I suggest to further clarify the readme files and provide usage examples.

**Comment by ofrei** [comment]
@bayramakdeniz Here is a fix for ldsc container: https://github.com/comorment/gwas/commit/686d972d25ced7ffecd83760a28cf303a7ff53a5
(following https://github.com/bulik/ldsc/issues/112#issuecomment-379690505 ).
I think this ticket can be closed - ldsc container works well.

**Comment by bayramakdeniz** [comment]
Yes, I checked it too and it works without an issue. Many thanks
