### ISSUE TITLE
Include Dockerfile for regenie3.sif

### ISSUE THREAD

**Issue by ofrei** [comorment/gwas#24]
There is regenie3.sif file in our google drive, but there is no corresponding Dockerfile.
If it's from external Docker image, ok to make something like this: https://github.com/comorment/gwas/blob/main/containers/saige/Dockerfile

**Comment by bayramakdeniz** [comment]
Done: https://github.com/comorment/gwas/tree/main/containers/regenie

It is not feasible to do in the same manner as we did in Saige since their docker container is not hosted in Docker Hub. Instead, I have modified  our script used to build singularity containers from Dockerfiles and get it

**Comment by ofrei** [comment]
@bayramakdeniz Thanks!
