### ISSUE TITLE
Setup dev box on NREC

### ISSUE THREAD

**Issue by ofrei** [comorment/gwas#27]
- Setup machine on NREC
- Install docker, singularity
- Install MATLAB from UiO
- Re-build ``matlabruntime.sif`` and pleiofdr / magicsquare executables, push them to https://github.com/comorment/containers

**Comment by ofrei** [comment]
@bayramakdeniz I fixed pleiofdr to exit upon completion, and include ``if(isdeployed==false)``. 
Could you pull these changes, re-build ``pleiofdr`` binary, and add it to ``github.com/comorment/containers/matlab`` folder (before setting up NREC machine)?

**Comment by ofrei** [comment]
@bayramakdeniz I'm a bit confused by ``pleiofdr`` behavior within matlabruntime.sif - I think ``pleiofdr`` always reads the same ``config.txt`` file. If I change ``config.txt`` or even delete it, ``pleiofdr`` still uses the same values from ``config.txt`` included in the demo example. Let's look closer into how pleiofdr is build and how to provide another config file to it.

**Comment by bayramakdeniz** [comment]
Yes, in fact, this is expected behavior in its current form. Hence what you desire is config.txt should be as an input of the application right? This is possible but we need to rebuild the application in a different manner. I can do that, are there some other files like that?

**Comment by ofrei** [comment]
@bayramakdeniz readme.m reads config.txt - and then depending on user parameters it will read a bunch of other .mat files (e.g. reference or summary statistics coverted to .mat format). It's important that user can customize this at runtime.
I'm happy to help fixing this once we have NREC dev box!

**Comment by ofrei** [comment]
Best to close this - we do have devbox and it generally works. As for matlabruntime.sif, we can discuss this separately.
