### ISSUE TITLE
Structure README.md file(s)

### ISSUE THREAD

**Issue by ofrei** [comorment/gwas#5]
I suggest to split README.md file into several files, for example:

* ``into.md`` with general info about docker, singularity, interactive / passive modes, mounting data to containers, etc. Basically, everything users need to know about docker and singularity that is not specific to your containers.
*  One file per each tool. For now I suggest we pick one tool, i.e. plink, and finalize it's readme file - and then proceed to other tools. 
* root-level ``README.md`` file, serving as list of contents - and  containing links to all other README files.

The readme file for each tool may have
* usage example
* version of the tool
* link to it's original help
* overview of demo data included (and it's location)

**Comment by bayramakdeniz** [comment]
The structure of the readme file has been changed as suggested (just for plink for now)

**Comment by ofrei** [comment]
I've messed ``docs`` folder - could you take a look there, and also at the README file in the root?
Also, I think we need to provide usage examples for other tools now included in ``gwas`` container, namely ``gcta, gctb, qctools, king, metal, vcftools, bcftools``. If they require additional data we also need to include it here https://github.com/norment/comorment_data

**Comment by bayramakdeniz** [comment]
Thanks, I will have a look. By the way, there are some examples of other tools here: https://github.com/comorment/gwas/blob/main/docs/others.md

I may clean and organize them if you like.

**Comment by ofrei** [comment]
Ah, right - this is very useful! Let's change these instructions to use singularity.
Is it possible to use existing bfile in <REF> /hapgen/chr21 (the 10K subjects, 150K SNPs dataset)?
If not, all new data needed to runs these tools should be added to  reference dataset (here: https://github.com/norment/comorment_data ). Please use GIT LFS when commit large files:
https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/configuring-git-large-file-storage

I've removed this code - do we need to re-add it into reference data?
```
RUN wget https://5c2d08d4-17d1-4dd8-bb49-f9593683e642.filesusr.com/archives/e7bc47_f74626b357ed453584e9e775713fe9ac.zip?dn=data_chapter10.zip && \
unzip -j  e7bc47_f74626b357ed453584e9e775713fe9ac.zip?dn=data_chapter10.zip  && \
rm -rf   e7bc47_f74626b357ed453584e9e775713fe9ac.zip?dn=data_chapter10.zip
```

**Comment by ofrei** [comment]
README files are getting a lot better :)
