### ISSUE TITLE
add "--no-home" to all singularity commands

### ISSUE THREAD

**Issue by ofrei** [comorment/gwas#7]
I suggest may want to add ``--no-home`` to our singularity commands, or at least clarify this in the README file.
I see there is also ``--pwd``, and some interference between this commands ( https://github.com/hpcng/singularity/issues/4077 ).

By default singularity mounts home directory, thus all software deployed in user's home folder may interfere with software provided by the container.

**Comment by bayramakdeniz** [comment]
it has been added
